### ISSUE TITLE
tokenizationのために外部コマンドを使えるオプション

### ISSUE THREAD

**Issue by theoremoon** [greymd/teip#12]
こんにちは！　シェル芸勉強会のLTをみてとても感動しました。

ところで teip は tokenization（？　ちゃんと読んだわけではないので誤用だったら申し訳ないです）を自前で実装しているようですが、これに外部コマンド（典型的にはgrepやcutなど？）を用いるオプションがあると便利かなと思いましたので提案してみます。

```
$ teip -e 'grep <pattern> -A 3' --row
```

マスキングに用いているコマンドが行指向なのか列指向なのかということを指定してあげる必要がありそうな気がしているのと、ナイーブな実装に比べて遅くなりがちであろうというのは懸念点ですが、現状teipで実装されていないようなマスキングを行いたいときのfallback先として実装しておくのはどうでしょうか？　ご意見を伺いたいです

**Comment by greymd** [comment]
マスキングに利用する範囲指定すらアウトソースするアプローチはかなり興味深いですね。
ぜひ検討したいです（技術的に可能ならば）。

少々想定する動作がわかっていないんですが、仮にマスキングをカスタマイズする`-e`オプションがあったとして、こんな挙動になるんですかね？

```
$ cat file
ABC
123
DEF

$ cat file | teip -e 'grep ABC -A 1' --row
[ABC]
[123]
DEF
=> grepによりABCと次の行がマッチする

$ cat file | teip -e 'cut -f3 -d,' --row -- sed 's/./@/g'
@@@
@@@
DEF
```

**Comment by theoremoon** [comment]
その想定です :+1:

**Comment by greymd** [comment]
下記のようなコマンドは技術的には無理と思ってます。
`teip`が`grep`を内部的に実行して`grep`の結果のパターンから選択範囲を推定する方法になると思うのですが、`grep`自体がマッチした個所以外の入力を削ってしまうので、正確にどの入力のどの箇所を選択してよいか`teip`は判断できないのではないかと（違う方式を想定していたらすみません）

```
teip -e 'grep <pattern> -A 3' --row
```

しかし、考えていてふと思ったのですが、下記なら技術的に可能かと思いました。
`-n`をつけています。

```
teip -e 'grep <pattern> -n -A 3'
```

`grep`の`-n`はマッチした行数を表示するオプションです。

```
$ echo {A..Z} | fmt -1 | grep D -n -A 3
4:D
5-E
6-F
7-G
```

つまり、`teip`は標準入力を一旦 `-e` のコマンドに渡しつつ、その結果の行頭の数字を抽出、その数字の行番号をマッチさせる。。。行指向オンリーのアプローチですが、この方法なら、下記のような芸当も可能です。

```
teip -e "sed -n '1~3='"
=> 1行目から3行ごとに選択

teip -e "sed -n '/AAA/,/BBB/='"
=> AAAから始まってBBBで終了する行まで選択

teip -e "awk 'NF==3{print NR}'"
=> 3 フィールド存在する行のみを選択

teip -e "seq 30 50"
=> 30行目から50行目を選択
```

これができればなかなか画期的な気がしています。

**Comment by theoremoon** [comment]
次のようなコードで実現できないかなと思っていましたが難しいですかね（Rustよくわからないので疑似コードです）？　正確に入力を判断できない例が思いついてないです。しかし例を見ていると行番号は簡潔かつ確実で良いですね。seqがうまく使えているのも良い感じですし、そちらの方が良いかも知れません

```
let stdin_dup = syscall::dup(0)
let output = Command("sh").arg("-c").arg(cmd).stdin(stdin_dup).output() // cmd にgrep "<pattern>" -A 3など

let stdin_iter = BufReader::new(io::stdin())
let cmd_iter = BufReader::new(output.stdout)

while !stdin_iter.eof() && !cmd_iter.eof() {
    while !stdin_iter.eof() && !cmd_iter.eof() {
        if *stdin_iter == *cmd_iter {
            // send
        }
        stdin_iter++
    }
    cmd_iter++
}
```

**Comment by greymd** [comment]
すみません`-A`などを利用する際に`grep`は重複した行を出力する可能性があると勘違いしてました。。
擬似コードもありがとうございます。腑に落ちました。`grep`の`-A`などを利用する際に出力される`--`をどう扱うかが少々悩ましいですがたしかに行けそうですね。ちょっと考えさせてください。

**Comment by theoremoon** [comment]
あー私は `--` を失念してましたね。grepなら `--group-separator=""` として空行は無視するとかですかね？
空行の扱いをどうするかも難しいですが……

**Comment by greymd** [comment]
いやー、悩ましいですね。行番号より、提案の方法のほうが直感的といえば直感的なんですよね。
とはいえ、`grep`専用という感じがします。`awk`を使うと想定と異なる状況になりそうで。。

```bash
$ cat hoge
AAA
BBB
AAA  ## <== 選択したい
CCC
AAA ## <== 選択したい
DDD

$ cat hoge | awk 'NR>2 && /AAA/'
AAA
AAA

## こうなりそう
$ teip -e "awk 'NR>2 && /AAA/'" < hoge
[AAA]
BBB
[AAA]
CCC
AAA
DDD
```

**Comment by theoremoon** [comment]
setbufみたいなので行バッファリングにして1行ずつ入出力をみる……みたいなワークアラウンドは思いつかないでもないですが流石に気持ち悪いですね。最終的な判断はおまかせします

**Comment by greymd** [comment]
二者択一というわけでなく、行番号も、提案方式も両方実装しちゃうって手もありだと思ってますが、やっぱり現時点だと先に行番号方式のほうが好きなので一旦そっち実装してどんなもんかベンチマークもとってみたいと思います。
（いずれにせよ、これを実装するだけで実装を予定していた機能２つ #3 #9 が不要になるので素晴らしい。。）

**Comment by greymd** [comment]
メモ：同じ行内でマッチさせたいのであればコロン区切りで数字を認識するって手も。。`ripgrep`が使える。

```
$ rg --column 'AA$' hoge
1:2:AAA
3:2:AAA
5:2:AAA
```

```
$ teip -e "rg --column 'AA$'" < hoge
A[AA]
BBB
A[AA]
CCC
A[AA]
DDD
```

**Comment by greymd** [comment]
こちらの機能、[v2.0.0](https://github.com/greymd/teip/releases/tag/v2.0.0) にて`-e` オプションとしてリリースしました。
行番号方式のみをとりあえず採用しました。

なお、この機能は match offload、としてます。

使ってみた感覚として、`teip` の既存の機能のスピード感を損なわず高速に動作するため、概ね満足しています。
が、メモリ使用率がちょっと高いかなぁと思ってます。そこは追々問題だと思う方がいれば検討します。
[ベンチマーク結果](https://github.com/greymd/teip/wiki/Memory-Usage-Benchmark)

余談ですが、v2.0.0で Tokenization という命名を変更し、Chunking にしました。
色々英語のドキュメントを読んで、標準出力を分割した単位は、Token というよりも Chunk のほうが自然だとおもったためです。

ここの Issue のおかげで大変有用かつ革新的な機能が実装できたと思います。
時間はかかってしまいましたが、改めて議論にお付き合いいただきありがとうございました！ @theoremoon 

それでは、クローズします。
