### ISSUE TITLE
Replace docopt with clap or structopt?

### ISSUE THREAD

**Issue by garasubo** [greymd/teip#16]
docoptはREADMEにかかれているように、あまり活発に更新されていないので、[clap](https://clap.rs/)ないし[structopt](https://docs.rs/crate/structopt/0.3.15)をコマンドライン引数の処理のために使うほうがヘルプなども自動生成されるので、そちらのほうがいいのかもしれないと思い提案させていただきます。
もし、何か特別な理由があってdocoptを選んだのであればcloseしてもらって構いません

**Comment by greymd** [comment]
docoptは単に私が別のプロジェクトで使い慣れており使っているだけですので、特にこだわりがあるわけではないです。
確かにdocopt.rsでも別のプロジェクトを推奨してますね。置き換える方向については賛成です。
どうしても優先度としては低いものになってしまうので、いつ私が手を動かせるかはわかりませんが……。
（Pull Requestを投げていただいても一向に構いません）。

**Comment by garasubo** [comment]
なるほど、了解です。金曜日あたりにまとまった時間がとれると思うので、どれくらい現状の機能の互換性を保てるか試しながらやってみます
