### ISSUE TITLE
Cheatsheetかcookbookがあれば最高です。

### ISSUE THREAD

**Issue by shinokada** [greymd/teip#26]
どこかにCheatsheetかcookbookがありませんか？
ぜひ使いたいです。
sed awkにできてteipにできない事はありますか？

**Comment by greymd** [comment]
機能ごとに索引がある一般的に言われるチートシートがあったら良いってことですかね？
なにかサンプルとなるようなページがあれば、ご紹介いただければ検討したいです。

> sed awkにできてteipにできない事はありますか？

sed/awk はプログラミング言語なので、たくさんあると思います。

**Comment by greymd** [comment]
cookbookというのはChefのような構成管理ツールで使われるものを想定していますかね？
また、Cheatsheet についても下記について知りたい状況です。
> 機能ごとに索引がある一般的に言われるチートシートがあったら良いってことですかね？

一旦本Issueはクローズしますが、上記お答えいただければ検討します。
